### ISSUE TITLE
Extracting file to BedrockConnect-1.0-SNAPSHOT.jar for brc_version 1.30 fails

### ISSUE THREAD

**Issue by archprlest** [strausmann/minecraft-bedrock-connect#1]
The folder structure for the brc_version 1.30 has changed and the  BedrockConnect-1.0-SNAPSHOT.jar is no longer at the root of the archive. This causes the easy-add to fail to extract the file and causes a restart loop in the docker image.  As you only need the jar file, it might be better to just get the jar file and not the archive to avoid issues with the folder in the archive.

https://github.com/Pugmatt/BedrockConnect/releases/download/{brc_version}/BedrockConnect-1.0-SNAPSHOT.jar

output from docker

2023-04-17 08:11:55 whitelist disabled
2023-04-17 08:11:55 custom_servers disabled
2023-04-17 08:11:55 Latest Bedrock Connect version is: 1.30
2023-04-17 08:11:55 Downloading now Bedrock Connect JAR
2023-04-17 08:11:55 2023/04/17 12:11:55 I! Retrieving https://github.com/Pugmatt/BedrockConnect/releases/download/1.30/BedrockConnect-setup.zip
2023-04-17 08:11:57 2023/04/17 12:11:57 E! unable to find requested file in archive

setting brc_version=1.29 and the container is able to start up.

**Comment by strausmann** [comment]
Thanks for the tip, I'll probably take a look tonight.

**Comment by strausmann** [comment]
Issue solved with release 2.1.0

**Comment by oscar-b** [comment]
@strausmann 
```
time="2023-04-25T15:50:49Z" level=debug msg="Using /data to match uid and gid"
time="2023-04-25T15:50:49Z" level=debug msg="Resolved UID=0 from match path"
time="2023-04-25T15:50:49Z" level=debug msg="Resolved GID=0 from match path"
whitelist disabled
custom_servers set to /config/serverlist.json
Latest Bedrock Connect version is: 1.31
Bedrock Connect Jar Source File: 'BedrockConnect-setup/BedrockConnect-1.0-SNAPSHOT.jar'
Downloading now Bedrock Connect JAR - version: 1.31
2023/04/25 15:50:50 I! Retrieving https://github.com/Pugmatt/BedrockConnect/releases/download/1.31/BedrockConnect-setup.zip
2023/04/25 15:50:51 E! unable to find requested file in archive
```

**Comment by archprlest** [comment]
Pugmatt Bedrock Connect releases 1.31 changed the zip archive folder structure back so the jar file is at the root level again.
 https://github.com/Pugmatt/BedrockConnect/releases/download/1.31/BedrockConnect-setup.zip.

**Comment by oscar-b** [comment]
Yeah reverting back to 2.0.0 works.

**Comment by strausmann** [comment]
really? so you can also employ the light

**Comment by strausmann** [comment]
Resolved 

https://github.com/Pugmatt/BedrockConnect/issues/404
