### ISSUE TITLE
Docker Image for arm64

### ISSUE THREAD

**Issue by TheDogg** [strausmann/minecraft-bedrock-connect#2]
would it be possible to have a docker image that can run on arm64 processors?

thanks

**Comment by masonen** [comment]
![image](https://github.com/strausmann/minecraft-bedrock-connect/assets/5367729/6e631681-a5d0-4cad-ba0c-6d84714d1ed9)
it is?

**Comment by masonen** [comment]
Ok. But the ARM image currently is not working @strausmann 

Fails with error 
```
time="2023-12-23T21:57:12Z" level=debug msg="Using /data to match uid and gid"
time="2023-12-23T21:57:12Z" level=debug msg="Resolved UID=0 from match path"
time="2023-12-23T21:57:12Z" level=debug msg="Resolved GID=0 from match path"
time="2023-12-23T21:57:12Z" level=fatal msg="Failed to run sub-command" error="fork/exec /opt/bedrock-entry.sh: exec format error"
```

After some debugging i found that the image digest used (https://hub.docker.com/layers/library/openjdk/22-ea-jdk-slim-bookworm/images/sha256-37867f656e947c1d2fa1e17aab69181c2911c6ad10f4bdfd0a6862a4ed8c7685?context=explore) is bound to their amd64 layer thus breaking the executability on arm. (the arm digest is https://hub.docker.com/layers/library/openjdk/22-ea-jdk-slim-bookworm/images/sha256-f3f34dcfba0e8a00fff69e872318b6b66dfa9152c5afab489799f52ef7134fac?context=explore)

I worked around that by changing the digest in a local docker file for now but it would be great if you could handle the digests for the multi arch build in your build pipeline?  Or maybe trust the stability of the tag and simply remove the digest from the image?

If needed i could prepare something here but earliest in jan :)

**Comment by strausmann** [comment]
@masonen thanks for the hint. I really slept there

https://git.strausmann.de/minecraft/bedrock-connect/-/issues/24

**Comment by masonen** [comment]
Pulled and run tag 24-arm-image-is-broken, works like charm.

**Comment by strausmann** [comment]
new stable release is now published.
