### ISSUE TITLE
Build new Version 1.42.1

### ISSUE THREAD

**Issue by codejanovic** [strausmann/minecraft-bedrock-connect#3]
Hi, 

the latest version of [BedrockConnect](https://github.com/Pugmatt/BedrockConnect) has the following [CVE GHSA-6h3m-c6fv-8hvh](https://github.com/CloudburstMC/Network/security/advisories/) and everyone using your images should update ASAP as well.

Cheers

**Comment by strausmann** [comment]
If Bedrock Connect has a new release to fix this security issue, all you need to do is create a new container from Minecraft Bedrock Connect. When starting the new container, the latest version of Bedrock Connect is always loaded and started in the standard. This makes this Docker container not to be rebuilt in a new release of Bedrock Connect.

**Comment by codejanovic** [comment]
I am sorry, thats my bad. Wasn't aware of that! Thanks for pointing out 👍
