### ISSUE TITLE
The packet_limit Docker environment variable is not passed to the https://github.com/strausmann/minecraft-bedrock-connect/blob/main/image/bedrock-entry.sh startup command.

### ISSUE THREAD

**Issue by pattarom** [strausmann/minecraft-bedrock-connect#6]
The packet_limit Docker environment variable is not passed to the https://github.com/strausmann/minecraft-bedrock-connect/blob/main/image/bedrock-entry.sh startup command.

This causes the error:
[Pugmatt/BedrockConnect] [nioEventLoopGroup-2-1] WARN org.cloudburstmc.netty.handler.codec.raknet.server.RakServerRateLimiter - [/192.168.1.209] Blocked because packet limit has been reached null disconnected

I opened a problem to Pugmatt who kindly analysed it and found that it was caused by the environment variable PACKET_LIMIT not being passed by the startup script "bedrock-entry.sh".

Thank you

**Comment by strausmann** [comment]
Let me check this.

**Comment by strausmann** [comment]
:tada: This FR is included in version 2.3.0 :tada:

The release is available on [GitLab release](https://git.strausmann.de/minecraft/bedrock-connect/-/releases/2.3.0).

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package: :rocket:
