### ISSUE TITLE
[Feature Request] Add environment variable for language file.

### ISSUE THREAD

**Issue by RealTriassic** [strausmann/minecraft-bedrock-connect#7]
https://github.com/Pugmatt/BedrockConnect?tab=readme-ov-file#change-wording-of-serverlist

**Comment by strausmann** [comment]
:tada: This FR is included in version 2.3.0 :tada:

The release is available on [GitLab release](https://git.strausmann.de/minecraft/bedrock-connect/-/releases/2.3.0).

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package: :rocket:
