### ISSUE TITLE
Usage of deprecated options

### ISSUE THREAD

**Issue by RealTriassic** [strausmann/minecraft-bedrock-connect#8]
https://github.com/Pugmatt/BedrockConnect/wiki/Deprecated-Database-Settings

**Comment by RealTriassic** [comment]
![image](https://github.com/user-attachments/assets/2fa37b35-37be-468e-a9dd-76a22b9f8466)

**Comment by RealTriassic** [comment]
![image](https://github.com/user-attachments/assets/905848d1-8b41-4400-aaaa-c4b17f2b708c)
Also add support for setting this option please, thank you

**Comment by strausmann** [comment]
https://git.strausmann.de/minecraft/bedrock-connect/-/issues/33

**Comment by strausmann** [comment]
🎉 This MR is included in version 2.5.0 🎉
The release is available on [GitLab release](https://git.strausmann.de/minecraft/bedrock-connect/-/releases/2.5.0).
Your [semantic-release](https://github.com/semantic-release/semantic-release) bot 📦 🚀
